name: Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      action:
        description: "Bicep action to run"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: "Deployment environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
      resource_group_name:
        description: "Resource group to delete when action is destroy and iac is bicep"
        required: false
        default: "rg-ghcp-demo-dev"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  infraDeployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Bicep What-If
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: >
          az deployment sub what-if
          --name bicep-whatif-${{ github.run_id }}
          --location eastus
          --template-file infra/deployment/main.bicep
          --parameters infra/deployment/main.${{ github.event.inputs.environment || 'development' }}.bicepparam

      - name: Bicep Deploy
        if: github.event.inputs.action == 'apply'
        run: >
          az deployment sub create
          --name bicep-deploy-${{ github.run_id }}
          --location eastus
          --template-file infra/deployment/main.bicep
          --parameters infra/deployment/main.${{ github.event.inputs.environment || 'development' }}.bicepparam

      - name: Bicep Destroy
        if: github.event.inputs.action == 'destroy'
        run: az group delete --name "${{ github.event.inputs.resource_group_name }}" --yes --no-wait